#conjunto de tasks para descargar, taggear y almacenar las distintas imágenes en el ACR
- name: Login to ACR
  containers.podman.podman_login:
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"
    registry: "{{ acr_name }}.azurecr.io"

- name: Pull nginx image
  containers.podman.podman_image:
    #    name: docker.io/nginx:latest
    name: docker.io/nginxdemos/hello:latest

- name: Tag nginx image for ACR
  containers.podman.podman_tag:
    #image: docker.io/nginx:latest
    image: docker.io/nginxdemos/hello:latest
    target_names:
      - "{{ acr_name }}.azurecr.io/nginx:casopractico2"

- name: Pull azure-vote-front image
  containers.podman.podman_image:
    name: docker.io/suhuruli/azure-vote-front:latest

- name: Tag azure-vote-front image for ACR
  containers.podman.podman_tag:
    #image: docker.io/nginx:latest
    image: docker.io/suhuruli/azure-vote-front:latest
    target_names:
      - "{{ acr_name }}.azurecr.io/azure-vote-front:casopractico2"

- name: Pull redis image
  containers.podman.podman_image:
    name: docker.io/redis:latest

- name: Tag redis image for ACR
  containers.podman.podman_tag:
    image: docker.io/redis:latest
    target_names:
      - "{{ acr_name }}.azurecr.io/redis:casopractico2"

- name: Push nginx image to ACR
  containers.podman.podman_image:
    name: "{{ acr_name }}.azurecr.io/nginx:casopractico2"
    push: true

- name: Push azure-vote-front image to ACR
  containers.podman.podman_image:
    name: "{{ acr_name }}.azurecr.io/azure-vote-front:casopractico2"
    push: true

- name: Push redis image to ACR
  containers.podman.podman_image:
    name: "{{ acr_name }}.azurecr.io/redis:casopractico2"
    push: true
